#
# Copyright 2020, Dave Slotter (W3DJS). All rights reserved.
#

- name: Download Amateur Radio Country Files
  hosts: all
  gather_facts: no
  tasks:

  - name: Create directory CTY_FILES
    file:
      path: "/home/{{ pi_user }}/hamradio/CTY_FILES"
      state: directory

  - name: Determine latest version of CTY_FILES on web
    shell: curl --silent "https://www.country-files.com/cty/download/" | grep -Po "\<a href=\"[0-9]+\/\"\>[0-9]+\/\<\/a\>" | tail -n 1 | grep -Po "[0-9]+" | uniq
    args:
      warn: no
    register: cty_version

  - local_action: command echo item
    with_items: cty_version.stdout_lines[0]

  - name: Download and Unarchive CTY {{ cty_version.stdout_lines[0] }} from http://www.country-files.com/
    unarchive:
      src: https://www.country-files.com/cty/download/{{ cty_version.stdout_lines[0] }}/cty-{{ cty_version.stdout_lines[0] }}.zip
      dest: "/home/{{ pi_user }}/hamradio/CTY_FILES"
      remote_src: yes

  - name: Create FLDigi data directory
    file:
      path: "/home/{{ pi_user }}/.fldigi"
      state: directory

  - name: Create WSJT-X data directory
    file:
      path: "/home/{{ pi_user }}/.local/share/WSJT-X"
      state: directory

  - name: Copy cty.dat to FLDigi
    shell: cp /home/{{ pi_user }}/hamradio/CTY_FILES/cty.dat /home/{{ pi_user }}/.fldigi

  - name: Copy cty.dat to WSJT-X
    shell: cp /home/{{ pi_user }}/hamradio/CTY_FILES/cty.dat /home/{{ pi_user }}/.local/share/WSJT-X

  - name: Determine latest version of BIGCTY on web
    shell: curl --silent "https://www.country-files.com/" | grep -Po "https://www.country-files.com/bigcty/download/bigcty-[0-9]+.zip" | head -n 1 | grep -Po "[0-9]+"
    args:
      warn: no
    register: bigcty_version

  - local_action: command echo item
    with_items: bigcty_version.stdout_lines[0]

  - name: Download and Unarchive Big CTY {{ bigcty_version.stdout_lines[0] }} from http://www.country-files.com/
    unarchive:
      src: https://www.country-files.com/bigcty/download/bigcty-{{ bigcty_version.stdout_lines[0] }}.zip
      dest: "/home/{{ pi_user }}/hamradio/CTY_FILES"
      remote_src: yes
