#
# Copyright 2020, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install JS8Call
  hosts: all
  tasks:

  - name: Create directory hamradio
    file:
      path: "/home/{{ pi_user }}/hamradio"
      state: directory

  - name: Install dependent libraries (Common)
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - libqt5multimedia5
      - libqt5multimedia5-plugins
      - libqt5serialport5

  - name: Install dependent libraries (ARM32)
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - libgfortran3
    when: ansible_architecture == "armhf" or ansible_architecture == "armv7l"

#
# Raspbian ARM
#

  - name: Determine latest version of JS8Call (ARM) on web
    shell: curl --silent "http://files.js8call.com/latest.html" | grep -Po "http://files.js8call.com/.*/js8call_.*_armhf.deb" | uniq | grep -Po "[0-9]+\.[0-9]+\.[0-9]+" | uniq
    args:
      warn: no
    register: download_date
    when: ansible_architecture == "armhf" or ansible_architecture == "armv7l" or ansible_architecture == "aarch64"

  - local_action: command echo item
    with_items: download_date.stdout_lines[0]
    when: ansible_architecture == "armhf" or ansible_architecture == "armv7l" or ansible_architecture == "aarch64"

  - name: Download JS8Call (ARM) {{ download_date.stdout_lines[0] }}
    get_url:
      url: http://files.js8call.com/{{ download_date.stdout_lines[0] }}/js8call_{{ download_date.stdout_lines[0] }}_armhf.deb
      dest: "/home/{{ pi_user }}/hamradio/js8call_{{ download_date.stdout_lines[0] }}_armhf.deb"
    when: ansible_architecture == "armhf" or ansible_architecture == "armv7l" or ansible_architecture == "aarch64"

  - name: Install JS8Call (ARM) {{ download_date.stdout_lines[0] }}
    become: yes
    apt:
      deb: "/home/{{ pi_user }}/hamradio/js8call_{{ download_date.stdout_lines[0] }}_armhf.deb"
    when: ansible_architecture == "armhf" or ansible_architecture == "armv7l" or ansible_architecture == "aarch64"

  - name: Remove JS8Call installer (ARM) {{ download_date.stdout_lines[0] }}
    file:
      path: "/home/{{ pi_user }}/hamradio/js8call_{{ download_date.stdout_lines[0] }}_armhf.deb"
      state: absent
    when: ansible_architecture == "armhf" or ansible_architecture == "armv7l" or ansible_architecture == "aarch64"

#
# Raspbian x86
#

  - name: Install dependent libraries (x86)
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - libc6:i386
    when: ansible_architecture == "i386"

  - name: Determine latest version of JS8Call (x86) on web
    shell: curl --silent "http://files.js8call.com/latest.html" | grep -Po "http://files.js8call.com/.*/js8call_.*_i386.deb" | uniq | grep -Po "[0-9]+\.[0-9]+\.[0-9]+" | uniq
    args:
      warn: no
    register: download_date
    when: ansible_architecture == "i386"

  - local_action: command echo item
    with_items: download_date.stdout_lines[0]
    when: ansible_architecture == "i386"

  - name: Download JS8Call (x86) {{ download_date.stdout_lines[0] }}
    get_url:
      url: http://files.js8call.com/{{ download_date.stdout_lines[0] }}/js8call_{{ download_date.stdout_lines[0] }}_i386.deb
      dest: "/home/{{ pi_user }}/hamradio/js8call_{{ download_date.stdout_lines[0] }}_i386.deb"
    when: ansible_architecture == "i386"

  - name: Install JS8Call (x86) {{ download_date.stdout_lines[0] }}
    become: yes
    apt:
      deb: "/home/{{ pi_user }}/hamradio/js8call_{{ download_date.stdout_lines[0] }}_i386.deb"
    when: ansible_architecture == "i386"

  - name: Remove JS8Call installer (x86) {{ download_date.stdout_lines[0] }}
    file:
      path: "/home/{{ pi_user }}/hamradio/js8call_{{ download_date.stdout_lines[0] }}_i386.deb"
      state: absent
    when: ansible_architecture == "i386"


#
# Common
#

  - name: Modify categories for js8call.desktop
    become: yes
    lineinfile:
      path: /usr/share/applications/js8call.desktop
      regexp: '^Categories=AudioVideo;Audio;HamRadio;'
      line: Categories=HamRadio Weak Signal
