#
# Copyright 2020, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install CMake Software
  hosts: all
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

  - name: Remove pre-installed cmake
    become: yes
    package:
      name: cmake
      state: absent
  
  - name: Create directory hamradio
    file:
      path: "/home/{{ pi_user }}/hamradio"
      state: directory

  - name: Install dependent libraries - libssl-dev
    become: yes
    package:
      name: libssl-dev
      state: present

  - name: Install dependent libraries - qt4-qmake
    become: yes
    package:
      name: qt4-qmake
      state: present

#
# Build and install CMake
#

  - name: Determine latest version of CMake on GitHub
    shell: curl --silent "https://github.com/Kitware/CMake/releases/" | grep -Po "cmake-[0-9]+.[0-9]+.[0-9]+.tar.gz" | head -n 1 | grep -Po "[0-9]+.[0-9]+.[0-9]+"
    args:
      warn: no
    register: cmake_version

  - local_action: command echo item
    with_items: cmake_version.stdout_lines[0]

  - name: Download and Unarchive CMake {{ cmake_version.stdout_lines[0] }} sources
    unarchive:
      src: https://github.com/Kitware/CMake/releases/download/v{{ cmake_version.stdout_lines[0] }}/cmake-{{ cmake_version.stdout_lines[0] }}.tar.gz
      dest: "/home/{{ pi_user }}/hamradio"
      remote_src: yes

  - name: Configure CMake {{ cmake_version.stdout_lines[0] }}
    command: ./configure
    args:
      chdir: "/home/{{ pi_user }}/hamradio/cmake-{{ cmake_version.stdout_lines[0] }}"

  - name: Build CMake {{ cmake_version.stdout_lines[0] }}
    command: make
    args:
      chdir: "/home/{{ pi_user }}/hamradio/cmake-{{ cmake_version.stdout_lines[0] }}"

  - name: Install CMake {{ cmake_version.stdout_lines[0] }}
    become: yes
    command: make install
    args:
      chdir: "/home/{{ pi_user }}/hamradio/cmake-{{ cmake_version.stdout_lines[0] }}"

  - name: Remove CMake {{ cmake_version.stdout_lines[0] }} build directory
    file:
      path: "/home/{{ pi_user }}/hamradio/cmake-{{ cmake_version.stdout_lines[0] }}"
      state: absent
