#
# Copyright 2020, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install SoapyFCDPP
  hosts: all
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

  - name: Create directory hamradio
    file:
      path: "/home/{{ pi_user }}/hamradio"
      state: directory

  - name: Install dependent libraries
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - gr-osmosdr
      - libfftw3-dev
      - libusb-1.0-0-dev
      - libhidapi-dev
      - libasound2-dev

  - name: Download latest SoapyFCDPP sources
    git:
      repo: https://github.com/pothosware/SoapyFCDPP
      dest: "/home/{{ pi_user }}/hamradio/SoapyFCDPP"

  - name: Create directory SoapyFCDPP/build
    file:
      path: "/home/{{ pi_user }}/hamradio/SoapyFCDPP/build"
      state: directory

  - name: Build SoapyFCDPP CMakeFiles
    command: cmake ..
    args:
      chdir: "/home/{{ pi_user }}/hamradio/SoapyFCDPP/build"

  - name: Build SoapyFCDPP
    command: make
    args:
      chdir: "/home/{{ pi_user }}/hamradio/SoapyFCDPP/build"

  - name: Install SoapyFCDPP
    become: yes
    command: make install
    args:
      chdir: "/home/{{ pi_user }}/hamradio/SoapyFCDPP/build"

  - name: Remove SoapyFCDPP build directory
    file:
      path: "/home/{{ pi_user }}/hamradio/SoapyFCDPP"
      state: absent
