#
# Copyright 2020, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install freedv
  hosts: all
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

  - name: Create directory hamradio
    file:
      path: "/home/{{ pi_user }}/hamradio"
      state: directory

  - name: Install dependent libraries for freedv-gui
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - libfltk1.3-dev
      - subversion
      - libwxgtk3.0-dev
      - portaudio19-dev
      - libusb-1.0-0-dev
      - libsamplerate0-dev
      - libasound2-dev
      - libao-dev
      - libgsm1-dev
      - libsndfile1-dev
      - libxft-dev
      - libxinerama-dev
      - libxcursor-dev
      - libspeex-dev
      - libspeexdsp-dev
      - libsndfile-dev
      - sox
#        - libjpeg9-dev

#
# Build and install FreeDV GUI
#

  - name: Download and Unarchive latest freedv-gui
    git:
      repo: https://github.com/drowe67/freedv-gui.git
      dest: "/home/{{ pi_user }}/hamradio/freedv-gui"

  - name: Build freedv-gui Binaries
    command: ./build_linux.sh
    args:
      chdir: "/home/{{ pi_user }}/hamradio/freedv-gui"

  - name: Install freedv-gui
    become: yes
    command: make install
    args:
      chdir: "/home/{{ pi_user }}/hamradio/freedv-gui/build_linux"

  - name: Modify categories for freedv.desktop
    become: yes
    lineinfile:
      path: /usr/local/share/applications/freedv.desktop
      regexp: '^Categories=GTK;GNOME;AudioVideo;Audio;HamRadio;'
      line: Categories=HamRadio

  - name: Remove freedv-gui build directory
    file:
      path: "/home/{{ pi_user }}/hamradio/freedv-gui"
      state: absent


#
# Codec2/FreeDV
#

  - name: Install dependent libraries
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - libspeexdsp-dev
      - libsamplerate0-dev

  - name: Git clone latest Codec2 sources
    git:
      repo: https://github.com/drowe67/codec2.git
      dest: "/home/{{ pi_user }}/hamradio/codec2"

  - name: Create directory codec2/build
    file:
      path: "/home/{{ pi_user }}/hamradio/codec2/build"
      state: directory

  - name: Build Codec2 CMakeFiles
    command: cmake -Wno-dev ..
    args:
      chdir: "/home/{{ pi_user }}/hamradio/codec2/build"

  - name: Build Codec2
    command: make
    args:
      chdir: "/home/{{ pi_user }}/hamradio/codec2/build"

  - name: Install Codec2
    become: yes
    command: make install
    args:
      chdir: "/home/{{ pi_user }}/hamradio/codec2/build"


  - name: Git clone latest Codec2 sources
    git:
      repo: https://github.com/drowe67/LPCNet
      dest: "/home/{{ pi_user }}/hamradio/LPCNet"

  - name: Create directory LPCNet/build
    file:
      path: "/home/{{ pi_user }}/hamradio/LPCNet/build"
      state: directory

  - name: Build LPCNet CMakeFiles
    command: cmake -DCODEC2_BUILD_DIR=/home/{{ pi_user }}/hamradio/codec2/build ..
    args:
      chdir: "/home/{{ pi_user }}/hamradio/LPCNet/build"

  - name: Build LPCNet
    command: make
    args:
      chdir: "/home/{{ pi_user }}/hamradio/LPCNet/build"

  - name: Install LPCNet
    become: yes
    command: make install
    args:
      chdir: "/home/{{ pi_user }}/hamradio/LPCNet/build"

  - name: Configure dynamic linker run-time bindings
    become: yes
    command: ldconfig

  - name: Remove LPCNet build directory
    file:
      path: "/home/{{ pi_user }}/hamradio/LPCNet"
      state: absent

  # Don't remove Codec2 until LPCNet is built
  - name: Remove Codec2 build directory
    file:
      path: "/home/{{ pi_user }}/hamradio/codec2"
      state: absent
