#
# Copyright 2020, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install SoapySDRPlay
  hosts: all
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
#    CXXFLAGS: -O2 -march=armv8-a
#    CFLAGS: -O2 -march=armv8-a
#    ARCH: arm
#    CROSS_COMPILE: arm-linux-gnueabihf-
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

  - name: Create directory hamradio
    file:
      path: "/home/{{ pi_user }}/hamradio"
      state: directory

  - name: Install dependent libraries
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - libusb-1.0-0-dev
      - expect

#
# Raspbian (ARM)
#

#  - name: Copy SDRPlay RSP Driver {{ sdrplay_arm_version }} (ARM)
#    copy:
#      src: "{{ playbook_dir }}/../files/SDRplay_RSP_API-ARM32-{{ sdrplay_arm_version }}.run"
#      dest: "/home/{{ pi_user }}/hamradio/SDRplay_RSP_API-ARM32-{{ sdrplay_arm_version }}.run"
#      mode: a+x
#        when: ansible_architecture == "armhf" or ansible_architecture == "armv7l" or ansible_architecture == "aarch64"

  - debug:
      msg: ansible_architecture is {{ ansible_architecture }}

  - name: Copy SDRPlay RSP Driver Installer {{ sdrplay_arm_version }} (ARM)
    copy:
      src: "{{ playbook_dir }}/../files/SDRplay_RSP_API-RPi-{{ sdrplay_arm_version }}.run"
      dest: "/home/{{ pi_user }}/hamradio/SDRplay_RSP_API-RPi-{{ sdrplay_arm_version }}.run"
      mode: a+x
    when: ansible_architecture == "armhf" or ansible_architecture == "armv7l" or ansible_architecture == "aarch64"

  - name: Copy SDRPlay Expect Script
    copy:
      src: "{{ playbook_dir }}/../files/sdrplay_api2_install.exp"
      dest: "/home/{{ pi_user }}/hamradio/sdrplay_api2_install.exp"
      mode: a+x
    when: ansible_architecture == "armhf" or ansible_architecture == "armv7l" or ansible_architecture == "aarch64"

  - name: Install SDRPlay RSP Driver {{ sdrplay_arm_version }} (ARM) using Expect Script
    become: yes
    command: ./sdrplay_api2_install.exp
    args:
      chdir: "/home/{{ pi_user }}/hamradio"
    when: ansible_architecture == "armhf" or ansible_architecture == "armv7l" or ansible_architecture == "aarch64"

 # - name: Remove SDRPlay RSP Driver Installer
 #   become: yes
 #   file:
 #     path: "/home/{{ pi_user }}/hamradio/SDRplay_RSP_API-ARM32-{{ sdrplay_arm_version }}.run"
 #     state: absent
 #   when: ansible_architecture == "armhf" or ansible_architecture == "armv7l"

  - name: Remove SDRPlay RSP Driver Installer
    become: yes
    file:
      path: "/home/{{ pi_user }}/hamradio/SDRplay_RSP_API-RPi-{{ sdrplay_arm_version }}.run"
      state: absent
    when: ansible_architecture == "armhf" or ansible_architecture == "armv7l" or ansible_architecture == "aarch64"

  - name: Remove SDRPlay Driver Expect Script
    become: yes
    file:
      path: "/home/{{ pi_user }}/hamradio/sdrplay_api2_install.exp"
      state: absent
    when: ansible_architecture == "armhf" or ansible_architecture == "armv7l" or ansible_architecture == "aarch64"

#
# Raspbian (x86)
#

#  - name: Copy SDRPlay Driver {{ sdrplay_x86_version }} (x86)
#    copy:
#      src: "{{ playbook_dir }}/../files/SDRplay_RSP_API-Linux-{{ sdrplay_x86_version }}.run"
#      dest: "/home/{{ pi_user }}/hamradio/SDRplay_RSP_API-Linux-{{ sdrplay_x86_version }}.run"
#    when: ansible_architecture == "i386"

#
# Build SoapySDRPlay Module
#

  - name: Download latest SoapySDRPlay sources
    git:
      repo: https://github.com/pothosware/SoapySDRPlay.git
      dest: "/home/{{ pi_user }}/hamradio/SoapySDRPlay"

  - name: Create directory SoapySDRPlay/build
    file:
      path: "/home/{{ pi_user }}/hamradio/SoapySDRPlay/build"
      state: directory

  - name: Build SoapySDRPlay CMakeFiles
    command: cmake ..
    args:
      chdir: "/home/{{ pi_user }}/hamradio/SoapySDRPlay/build"

  - name: Build SoapySDRPlay
    command: make
    args:
      chdir: "/home/{{ pi_user }}/hamradio/SoapySDRPlay/build"

  - name: Install SoapySDRPlay
    become: yes
    command: make install
    args:
      chdir: "/home/{{ pi_user }}/hamradio/SoapySDRPlay/build"

  - name: Remove SoapySDRPlay build directory
    file:
      path: "/home/{{ pi_user }}/hamradio/SoapySDRPlay"
      state: absent
