#
# Copyright 2020, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install Chirp Software
  hosts: all
  gather_facts: no
  tasks:

  - name: Create directory hamradio
    file:
      path: "/home/{{ pi_user }}/hamradio"
      state: directory

  - name: Install Chirp prerequisite packages
    become: yes
    package:
      name: "{{ item }}"
      state: present
    with_items:
      - python-gtk2
      - python-serial
      - python-libxml2

  - name: Determine latest version of Chirp on web
    shell: curl --silent "https://trac.chirp.danplanet.com/chirp_daily/LATEST/" | grep -Po "chirp-daily-[0-9]+.tar.gz" | uniq | egrep -o "[0-9]+"
    args:
      warn: no
    register: download_date

  - local_action: command echo item
    with_items: download_date.stdout_lines[0]

  - name: Download and Unarchive Chirp {{ download_date.stdout_lines[0] }}
    unarchive:
      src: "https://trac.chirp.danplanet.com/chirp_daily/LATEST/chirp-daily-{{ download_date.stdout_lines[0] }}.tar.gz"
      dest: "/home/{{ pi_user }}/hamradio/"
      remote_src: yes
      validate_certs: no

  - name: Install Chirp {{ download_date.stdout_lines[0] }}
    become: yes
    command: python setup.py install
    args:
      chdir: "/home/{{ pi_user }}/hamradio/chirp-daily-{{ download_date.stdout_lines[0] }}"

  - name: Modify categories for chirp.desktop
    become: yes
    lineinfile:
      path: /usr/local/share/applications/chirp.desktop
      regexp: '^Categories=Hamradio;Programming;Handheld;Radio;Amateur;Programmer'
      line: Categories=HamRadio

  - name: Remove Chirp {{ download_date.stdout_lines[0] }} build directory
    become: yes
    file:
      path: "/home/{{ pi_user }}/hamradio/chirp-daily-{{ download_date.stdout_lines[0] }}"
      state: absent
