#
# Copyright 2020, Dave Slotter (W3DJS). All rights reserved.
#

- name: Install SoapyRTLSDR
  hosts: all
  environment:
    # Build-Time Tuning:
    CXXFLAGS: -O2 -march=native -mtune=native
    CFLAGS: -O2 -march=native -mtune=native
    MAKEFLAGS: -j {{ ansible_processor_vcpus }}
  tasks:

  - name: Create directory hamradio
    file:
      path: "/home/{{ pi_user }}/hamradio"
      state: directory

  - name: Install dependent libraries
    become: yes
    package:
      name: libusb-1.0-0-dev
      state: present

  - name: Download latest RTL-SDR sources
    git:
      repo: https://github.com/steve-m/librtlsdr
      dest: "/home/{{ pi_user }}/hamradio/librtlsdr"

  - name: Create directory librtlsdr/build
    file:
      path: "/home/{{ pi_user }}/hamradio/librtlsdr/build"
      state: directory

  - name: Build RTL-SDR CMakeFiles
    command: cmake ..
    args:
      chdir: "/home/{{ pi_user }}/hamradio/librtlsdr/build"

  - name: Build RTL-SDR
    command: make
    args:
      chdir: "/home/{{ pi_user }}/hamradio/librtlsdr/build"

  - name: Install RTL-SDR
    become: yes
    command: make install
    args:
      chdir: "/home/{{ pi_user }}/hamradio/librtlsdr/build"

  - name: Remove RTL-SDR build directory
    file:
      path: "/home/{{ pi_user }}/hamradio/librtlsdr"
      state: absent

  - name: Download latest SoapyRTLSDR sources
    git:
      repo: https://github.com/pothosware/SoapyRTLSDR.git
      dest: "/home/{{ pi_user }}/hamradio/SoapyRTLSDR"

  - name: Create directory SoapyRTLSDR/build
    file:
      path: "/home/{{ pi_user }}/hamradio/SoapyRTLSDR/build"
      state: directory

  - name: Build SoapyRTLSDR CMakeFiles
    command: cmake ..
    args:
      chdir: "/home/{{ pi_user }}/hamradio/SoapyRTLSDR/build"

  - name: Build SoapyRTLSDR
    command: make
    args:
      chdir: "/home/{{ pi_user }}/hamradio/SoapyRTLSDR/build"

  - name: Install SoapyRTLSDR
    become: yes
    command: make install
    args:
      chdir: "/home/{{ pi_user }}/hamradio/SoapyRTLSDR/build"

  - name: Remove SoapyRTLSDR build directory
    file:
      path: "/home/{{ pi_user }}/hamradio/SoapyRTLSDR"
      state: absent
